export type ThemeProfileId =
  | "calm_focus"
  | "low_stim_emergency"
  | "dyslexia_readable"
  | "dyscalculia_numeric_relief"
  | "visual_processing_safe"
  | "apd_assist"
  | "executive_function_support"
  | "motor_friendly"
  | "adhd_dopamine_balanced"
  | "adhd_hyperfocus"
  | "autism_predictable"
  | "tourette_tic_friendly"
  | "standard_red_green";

export type ThemeProfile = {
  id: ThemeProfileId;
  label: string;
  bgTop: string;
  bgBottom: string;
  panel: string;
  text: string;
  grid: string;
  borderA: string;
  borderB: string;
  upColor: string;
  downColor: string;
  wickUpColor: string;
  wickDownColor: string;
  borderUpColor: string;
  borderDownColor: string;
  glow: "Low" | "Medium" | "High";
  spacing: "Tight" | "Normal" | "Wide";
  dataDensity: "Low" | "Medium" | "High";
  motion: "Off" | "Soft" | "Normal";
};

export const themeProfiles: Record<ThemeProfileId, ThemeProfile> = {
  calm_focus: {
    id: "calm_focus",
    label: "Calm Focus",
    bgTop: "#0b0e14",
    bgBottom: "#05070c",
    panel: "rgba(8,15,28,0.92)",
    text: "#dbeafe",
    grid: "rgba(255,255,255,0.045)",
    borderA: "#00E5FF",
    borderB: "#FF1493",
    upColor: "#00E5FF",
    downColor: "#FF1493",
    wickUpColor: "#00E5FF",
    wickDownColor: "#FF1493",
    borderUpColor: "#00E5FF",
    borderDownColor: "#FF1493",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Soft",
  },
  low_stim_emergency: {
    id: "low_stim_emergency",
    label: "Low Stimulation",
    bgTop: "#05070b",
    bgBottom: "#000000",
    panel: "rgba(5,7,11,0.96)",
    text: "#cbd5e1",
    grid: "rgba(148,163,184,0.08)",
    borderA: "#475569",
    borderB: "#64748b",
    upColor: "#94a3b8",
    downColor: "#64748b",
    wickUpColor: "#94a3b8",
    wickDownColor: "#64748b",
    borderUpColor: "#94a3b8",
    borderDownColor: "#64748b",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Off",
  },
  dyslexia_readable: {
    id: "dyslexia_readable",
    label: "Reading Support",
    bgTop: "#08131f",
    bgBottom: "#020617",
    panel: "rgba(8,19,31,0.92)",
    text: "#f8fafc",
    grid: "rgba(226,232,240,0.14)",
    borderA: "#4D00FF",
    borderB: "#60a5fa",
    upColor: "#5c00ff",
    downColor: "#ff9100",
    wickUpColor: "#9d6bff",
    wickDownColor: "#ffab40",
    borderUpColor: "#5c00ff",
    borderDownColor: "#ff9100",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Soft",
  },
  dyscalculia_numeric_relief: {
    id: "dyscalculia_numeric_relief",
    label: "Numeric Relief",
    bgTop: "#0a1220",
    bgBottom: "#020617",
    panel: "rgba(10,18,32,0.94)",
    text: "#e2e8f0",
    grid: "rgba(148,163,184,0.10)",
    borderA: "#4D00FF",
    borderB: "#f59e0b",
    upColor: "#4D00FF",
    downColor: "#fb7185",
    wickUpColor: "#4D00FF",
    wickDownColor: "#fda4af",
    borderUpColor: "#4D00FF",
    borderDownColor: "#fb7185",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Soft",
  },
  visual_processing_safe: {
    id: "visual_processing_safe",
    label: "Visual Ease",
    bgTop: "#06111b",
    bgBottom: "#01040a",
    panel: "rgba(6,17,27,0.95)",
    text: "#dbeafe",
    grid: "rgba(147,197,253,0.08)",
    borderA: "#60a5fa",
    borderB: "#a78bfa",
    upColor: "#60a5fa",
    downColor: "#fca5a5",
    wickUpColor: "#93c5fd",
    wickDownColor: "#fecaca",
    borderUpColor: "#60a5fa",
    borderDownColor: "#fca5a5",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Off",
  },
  apd_assist: {
    id: "apd_assist",
    label: "Reduced Signal Load",
    bgTop: "#08131d",
    bgBottom: "#020617",
    panel: "rgba(8,19,29,0.93)",
    text: "#e2e8f0",
    grid: "rgba(148,163,184,0.14)",
    borderA: "#2dd4bf",
    borderB: "#fb7185",
    upColor: "#2dd4bf",
    downColor: "#fb7185",
    wickUpColor: "#5eead4",
    wickDownColor: "#fda4af",
    borderUpColor: "#2dd4bf",
    borderDownColor: "#fb7185",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Soft",
  },
  executive_function_support: {
    id: "executive_function_support",
    label: "Task Structure",
    bgTop: "#07101b",
    bgBottom: "#020617",
    panel: "rgba(7,16,27,0.94)",
    text: "#e2e8f0",
    grid: "rgba(148,163,184,0.10)",
    borderA: "#38bdf8",
    borderB: "#f97316",
    upColor: "#38bdf8",
    downColor: "#f97316",
    wickUpColor: "#7dd3fc",
    wickDownColor: "#fdba74",
    borderUpColor: "#38bdf8",
    borderDownColor: "#f97316",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Soft",
  },
  motor_friendly: {
    id: "motor_friendly",
    label: "Large Target Mode",
    bgTop: "#09111f",
    bgBottom: "#020617",
    panel: "rgba(9,17,31,0.94)",
    text: "#f1f5f9",
    grid: "rgba(148,163,184,0.12)",
    borderA: "#4D00FF",
    borderB: "#f87171",
    upColor: "#5c00ff",
    downColor: "#ff5252",
    wickUpColor: "#9d6bff",
    wickDownColor: "#ff867f",
    borderUpColor: "#5c00ff",
    borderDownColor: "#ff5252",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Off",
  },
  adhd_dopamine_balanced: {
    id: "adhd_dopamine_balanced",
    label: "Balanced Energy",
    bgTop: "#09091b",
    bgBottom: "#020617",
    panel: "rgba(9,9,27,0.93)",
    text: "#f8fafc",
    grid: "rgba(34,211,238,0.16)",
    borderA: "#22d3ee",
    borderB: "#f472b6",
    upColor: "#00eaff",
    downColor: "#ff2dfc",
    wickUpColor: "#80f4ff",
    wickDownColor: "#ff96fd",
    borderUpColor: "#00eaff",
    borderDownColor: "#ff2dfc",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Normal",
  },
  adhd_hyperfocus: {
    id: "adhd_hyperfocus",
    label: "Hyperfocus",
    bgTop: "#090510",
    bgBottom: "#000000",
    panel: "rgba(9,5,16,0.95)",
    text: "#ffffff",
    grid: "rgba(255,212,0,0.16)",
    borderA: "#00f5ff",
    borderB: "#ff3dff",
    upColor: "#00f5ff",
    downColor: "#ff00ff",
    wickUpColor: "#80faff",
    wickDownColor: "#ff80ff",
    borderUpColor: "#00f5ff",
    borderDownColor: "#ff00ff",
    glow: "High",
    spacing: "Tight",
    dataDensity: "High",
    motion: "Normal",
  },
  autism_predictable: {
    id: "autism_predictable",
    label: "Autism - Predictable",
    bgTop: "#07111a",
    bgBottom: "#020617",
    panel: "rgba(7,17,26,0.94)",
    text: "#f1f5f9",
    grid: "rgba(148,163,184,0.14)",
    borderA: "#4D00FF",
    borderB: "#93c5fd",
    upColor: "#4D00FF",
    downColor: "#93c5fd",
    wickUpColor: "#4D00FF",
    wickDownColor: "#bfdbfe",
    borderUpColor: "#4D00FF",
    borderDownColor: "#93c5fd",
    glow: "Low",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Off",
  },
  tourette_tic_friendly: {
    id: "tourette_tic_friendly",
    label: "Minimal Motion",
    bgTop: "#05070b",
    bgBottom: "#000000",
    panel: "rgba(5,7,11,0.96)",
    text: "#e2e8f0",
    grid: "rgba(148,163,184,0.08)",
    borderA: "#4D00FF",
    borderB: "#fbcfe8",
    upColor: "#4D00FF",
    downColor: "#fbcfe8",
    wickUpColor: "#4D00FF",
    wickDownColor: "#fce7f3",
    borderUpColor: "#4D00FF",
    borderDownColor: "#fbcfe8",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Off",
  },
  standard_red_green: {
    id: "standard_red_green",
    label: "Standard Chart (Red & Green)",
    bgTop: "#131722",
    bgBottom: "#0b0e14",
    panel: "rgba(19,23,34,0.96)",
    text: "#d1d4dc",
    grid: "rgba(54,60,78,0.55)",
    borderA: "#26a69a",
    borderB: "#ef5350",
    upColor: "#26a69a",
    downColor: "#ef5350",
    wickUpColor: "#26a69a",
    wickDownColor: "#ef5350",
    borderUpColor: "#26a69a",
    borderDownColor: "#ef5350",
    glow: "Low",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Soft",
  },
};
