/** Accurate plain-English descriptions for Encyclopedia of Indicators entries. */
export const INDICATOR_DESCRIPTIONS: Record<string, string> = {
  "Acceleration Bands": "Volatility bands plotted above and below a moving average of typical price. Price breaking the upper or lower band can signal strong acceleration in that direction.",
  "Accumulation/Distribution Line": "A cumulative volume-flow line that rises when the close finishes near the high of the range and falls when it finishes near the low. Used to confirm price trends or spot divergence.",
  "Advance/Decline Line": "Market-breadth cumulative total of advancing minus declining issues. Rising A/D with rising prices confirms a healthy advance; divergence can warn of weakening breadth.",
  "Advance-Decline Ratio": "Ratio of advancing stocks to declining stocks over a period. Extreme readings often mark short-term overbought or oversold breadth conditions.",
  "ADX (Average Directional Index)": "Trend-strength oscillator (typically 0–100). Readings above ~25 suggest a trending market; below ~20 suggest a range. ADX does not show direction by itself.",
  "Alligator Indicator": "Bill Williams trend tool using three smoothed moving averages (jaw, teeth, lips). When the lines fan apart the trend is active; when they intertwine the market is sleeping.",
  "Alpha": "Excess return of an asset or strategy relative to a benchmark after adjusting for risk. Positive alpha means outperformance versus the expected return from beta alone.",
  "Andrews Pitchfork": "Three parallel trend lines drawn from a pivot high/low and two subsequent pivots. Price often gravitates toward the median line; outer tines act as support/resistance.",
  "Aroon Indicator": "Two lines (Aroon Up / Aroon Down) measuring how recently price made a new high or low within a lookback. High Up and low Down favors an uptrend, and vice versa.",
  "Aroon Oscillator": "Single line equal to Aroon Up minus Aroon Down. Positive values favor bullish trend strength; negative values favor bearish trend strength.",
  "ATR (Average True Range)": "Average of true range (high-low accounting for gaps). Measures volatility only—not direction. Widely used for stop distances and position sizing.",
  "Average Price": "Simple average of open, high, low, and close for a bar. Used as a smoother mid-price reference for overlays and calculations.",
  "Average Volume": "Mean traded volume over a lookback window. Comparing current volume to average highlights unusual participation.",
  "Awesome Oscillator": "Bill Williams histogram of a 5-period SMA of midpoint minus a 34-period SMA. Above zero favors bullish momentum; saucer and twin-peak patterns are classic reads.",
  "Balance of Power": "Oscillator comparing buying pressure to selling pressure using open/close relative to the bar range. Helps gauge which side dominated a session.",
  "Beta": "Sensitivity of an asset’s returns to a benchmark’s returns. Beta > 1 means more volatile than the market; beta < 1 means less volatile.",
  "Bid-Ask Spread": "Difference between the best ask and best bid. Wider spreads imply higher trading costs and often thinner liquidity.",
  "Bollinger Bands": "A middle SMA with upper/lower bands at a multiple of standard deviation. Band squeezes precede volatility expansions; touches can mark extremes in ranging markets.",
  "Bollinger Band Width": "Distance between upper and lower Bollinger Bands, often normalized. Falling width = squeeze; rising width = expanding volatility.",
  "Breadth Thrust": "Breadth thrust measures a sudden surge in advancing issues versus total issues. Historically associated with the start of strong bullish phases when thresholds are met.",
  "Bull Bear Power": "Elder’s Bull Power (high − EMA) and Bear Power (low − EMA). Used with trend filters to spot when bulls or bears are gaining or losing control.",
  "Bull Market Support Band": "A dual moving-average band (commonly 20-week SMA and 21-week EMA) used as a dynamic support zone in longer-term bull markets.",
  "Camarilla Pivot Points": "Intraday support/resistance levels derived from the prior day’s high, low, and close with specific multipliers. Popular for mean-reversion and breakout levels.",
  "Candlestick Pattern Index": "Composite score summarizing recognized candlestick pattern signals over recent bars to quantify pattern-based bias.",
  "CCI (Commodity Channel Index)": "Momentum oscillator measuring price deviation from its statistical mean. Classic thresholds (±100) flag extended conditions; zero-line crosses show momentum shifts.",
  "Center of Gravity": "John Ehlers oscillator that estimates a center-of-mass of recent prices. Designed for early turning-point signals with relatively low lag.",
  "Chaikin Money Flow": "Volume-weighted accumulation measure over N periods. Positive CMF suggests buying pressure; negative suggests selling pressure.",
  "Chaikin Oscillator": "MACD-style difference of EMAs applied to the Accumulation/Distribution line. Highlights acceleration or deceleration in money flow.",
  "Chaikin Volatility": "Rate of change of an EMA of the high-low range. Rising values show expanding ranges; falling values show a squeeze in bar width.",
  "Chande Forecast Oscillator": "Compares the close to a linear-regression forecast of price. Positive when price is above the forecast; negative when below.",
  "Chande Momentum Oscillator": "Momentum oscillator scaled roughly −100 to +100 using up versus down closes. Often paired with a moving average signal line.",
  "Channel Index": "Generic channel-position measure showing where price sits between recent highs and lows—useful for mean-reversion and breakout context.",
  "Closing Price Location Value": "Locates the close within the bar’s high-low range (0–1 style). Closes near highs show buying dominance; near lows show selling dominance.",
  "Commitment of Traders (COT)": "Weekly CFTC positioning of commercials, non-commericals, and non-reportables. Used as a sentiment/positioning overlay for futures markets.",
  "Commodity Selection Index": "Welles Wilder index ranking commodities by directional movement and volatility-adjusted opportunity for trend systems.",
  "Composite Index": "Breadth/momentum hybrid (often associated with RSI divergence analysis) that can reveal internal weakness before price RSI does.",
  "Connors RSI": "Composite of RSI, streak RSI, and percentile rank of consecutive closes. Built for short-term mean-reversion timing.",
  "Coppock Curve": "Long-term momentum curve from smoothed rate-of-change sums. Historically used for major equity bottom signals when it turns up from deep negatives.",
  "Correlation Coefficient": "Statistical correlation (−1 to +1) between two series. Near +1 = move together; near −1 = move opposite; near 0 = little linear relationship.",
  "Cumulative Delta": "Running total of aggressive buy volume minus sell volume (order-flow). Rising cumulative delta with flat price can hint at absorption.",
  "Detrended Price Oscillator": "Removes a longer-cycle trend from price to highlight shorter cycles. Useful for timing oscillations around a trend.",
  "Demand Index": "Volume/price pressure index comparing buying and selling demand. Divergences with price can flag exhaustion.",
  "DeMarker Indicator": "Compares high-to-high and low-to-low differences to gauge exhaustion. Extreme readings suggest overbought/oversold risk of pause or reversal.",
  "Directional Movement Index (DMI)": "Wilder’s +DI and −DI lines measuring upside versus downside directional movement. Often plotted with ADX for trend direction plus strength.",
  "Donchian Channels": "Highest high and lowest low over N periods (turtle-style). Breakouts beyond the channel are classic trend-following entries.",
  "Double EMA": "DEMA — 2×EMA minus EMA-of-EMA. A lower-lag moving average used as a faster trend overlay than a single EMA of the same length.",
  "Downside Deviation": "Volatility of returns below a threshold (often zero or a MAR). Emphasizes harmful volatility used in Sortino-style analysis.",
  "DPO": "Detrended Price Oscillator (short name). Centers a displaced moving average to isolate cycle highs/lows without the longer trend.",
  "Ease of Movement": "Volume-adjusted price-move oscillator. High readings mean price advanced easily on light volume; low readings mean heavy resistance.",
  "Elder Force Index": "Price change × volume, usually smoothed. Shows how much force bulls or bears exerted; zero-line and divergences are key reads.",
  "Elder Ray": "Bull Power and Bear Power relative to an EMA trend filter. Used to time entries with the prevailing EMA direction.",
  "Elliott Wave Oscillator": "Difference between a short and longer SMA used as a wave-momentum aid. Peaks/troughs often align with impulsive wave strength.",
  "EMA (Exponential Moving Average)": "Moving average that weights recent prices more heavily. Responds faster than SMA; cornerstone of many trend and MACD systems.",
  "Envelope Indicator": "Percentage bands above and below a moving average. Price outside the envelope can mark stretch; inside frames a normal trading range.",
  "Fair Value Gap": "Imbalance candle zone where price moved so fast that a wick/body gap was left. Traders watch these inefficiencies as magnets for later fills.",
  "Fast Stochastic": "Raw %K/%D stochastic comparing close to the recent high-low range. Sensitive oscillator for short-term overbought/oversold swings.",
  "Fibonacci Arcs": "Arcs drawn through Fibonacci ratios from a swing, projecting curved support/resistance as time and price interact.",
  "Fibonacci Channels": "Parallel channels spaced by Fibonacci ratios from a trend line, framing potential pullback and extension lanes.",
  "Fibonacci Expansion": "Projects extension targets beyond a swing using Fibonacci multiples (e.g., 1.272, 1.618) for take-profit mapping.",
  "Fibonacci Fan": "Trend lines from a swing through Fibonacci ratios, creating angled support/resistance rays.",
  "Fibonacci Retracement": "Horizontal levels at key Fibonacci ratios (23.6%, 38.2%, 50%, 61.8%, 78.6%) between a swing high and low for pullback entries.",
  "Fisher Transform": "Transforms price into a near-Gaussian distribution to sharpen turning points. Crosses and extremes can flag reversals early.",
  "Force Index": "Same family as Elder Force Index: change in price times volume, smoothed to read buying/selling force.",
  "Fractal Indicator": "Bill Williams fractals mark local five-bar highs/lows. Often used as breakout triggers or stop references.",
  "Gann Fan": "Geometric fan lines from a pivot at Gann angles (e.g., 1×1). Used for time/price geometric support and resistance.",
  "Gann Grid": "Grid of Gann angles overlaying price to frame geometric swing structure and reaction zones.",
  "Gann Square": "Square-of-nine / Gann square geometry projecting price-time relationships from a significant pivot.",
  "Golden Cross": "Bullish moving-average event when a shorter MA crosses above a longer MA (commonly 50 over 200). Signals improving longer-term trend.",
  "Gravity Center": "Center-of-gravity style oscillator highlighting cyclical turning points with reduced lag versus classic momentum tools.",
  "Gross Domestic Product (GDP)": "Macro measure of total economic output. Growth/contraction prints move rates, FX, and risk assets via growth expectations.",
  "Harmonic Patterns": "Geometric Fibonacci price patterns (Gartley, Bat, Butterfly, etc.) aiming to map potential reversal zones (PRZs).",
  "Heikin Ashi": "Averaged candlestick representation that smooths noise. Strong consecutive colored bars highlight trend; doji-like bars hint at pause.",
  "Historical Volatility": "Realized volatility of past returns (often annualized). Rising HV means larger recent price swings.",
  "Hull Moving Average": "Alan Hull’s low-lag moving average designed to stay smooth while reducing lag versus traditional MAs.",
  "Ichimoku Cloud": "Full system with Conversion/Base lines, Lagging Span, and Cloud (Span A/B). Cloud color/position frames trend, support, and momentum.",
  "Implied Volatility": "Options market’s forecast of future volatility embedded in premiums. Rising IV often means higher expected movement/risk premium.",
  "Inflation Rate": "Pace of price-level increase (CPI/PCE style). Affects real yields, central-bank policy, and sector rotation.",
  "Interest Coverage Ratio": "Fundamental ratio of EBIT (or similar) to interest expense. Higher coverage means easier debt-service capacity.",
  "Interest Rate Differential": "Gap between two countries’ interest rates. A key driver of FX carry and forward pricing.",
  "Internal Bar Strength": "Position of the close within the high-low range. Values near 1 show closes at highs; near 0 at lows.",
  "Jurik Moving Average": "Proprietary low-noise adaptive moving average known for smoothness with relatively controlled lag.",
  "Kairi Relative Index": "Percentage distance of price from a moving average. Extreme deviations can flag stretch for mean reversion.",
  "Keltner Channels": "EMA midline with ATR-based bands. Similar use-case to Bollinger but volatility scaled by ATR instead of standard deviation.",
  "Know Sure Thing (KST)": "Martin Pring’s summed, weighted ROC oscillator across multiple cycles. Signal-line crosses mark multi-timeframe momentum shifts.",
  "Lagging Span": "Ichimoku’s Chikou Span—current close plotted back N periods. Used to confirm momentum versus past price.",
  "Linear Regression": "Best-fit trend line through recent closes. Slope shows drift; residuals show how extended price is from fair trend.",
  "Linear Regression Channel": "Regression midline with parallel standard-error (or sigma) channels. Frames statistically typical price travel.",
  "Liquidity Void": "A fast displacement leaving thin traded area (related to fair value gaps). Price often revisits to rebalance liquidity.",
  "Local Volatility": "Model volatility that varies with strike/spot and time, used in options surface analysis beyond a single IV number.",
  "Log Return": "Natural log of price ratios between periods. Preferred in quantitative work because log returns add over time.",
  "MACD": "Difference between fast and slow EMAs with a signal EMA and optional histogram. Tracks trend momentum and crossover timing.",
  "MACD Histogram": "MACD line minus signal line. Expanding histogram shows strengthening momentum; shrinking shows fading momentum.",
  "Market Breadth": "Family of measures (A/D, % above MA, new highs/lows) describing how widely participation supports an index move.",
  "Market Facilitation Index": "Bill Williams: (high−low)/volume. Rising MFI with rising volume shows efficient directional facilitation.",
  "Market Profile": "TPO/price-auction distribution showing where time was spent at each price. Highlights value area, POC, and balance vs imbalance.",
  "Market Sentiment Index": "Composite sentiment gauge from surveys, positioning, or price/volume proxies. Extremes can be contrarian inputs.",
  "Mass Index": "Volatility bulge detector from dual-smoothed high-low ranges. A “reversal bulge” setup is watched near classic thresholds (~27 then 26.5).",
  "McClellan Oscillator": "Breadth oscillator from EMAs of advancing−declining issues. Overbought/oversold breadth and zero-line crosses are key.",
  "McClellan Summation Index": "Cumulative total of the McClellan Oscillator. Tracks longer-term breadth trends and major turns.",
  "Median Price": "(High + Low) / 2 for each bar. Simple mid-range price used in overlays and oscillators.",
  "Momentum": "Raw price change over N periods (close − close[N]). Rising momentum confirms thrust; divergences can warn of exhaustion.",
  "Money Flow Index": "Volume-weighted RSI-style oscillator (0–100). Incorporates typical price and volume; 80/20 style extremes are common references.",
  "Moving Average": "Generic average of past closes (SMA/EMA/etc.). Smooths noise to define trend direction and dynamic support/resistance.",
  "Moving Average Envelope": "Percentage bands around a moving average (envelope). Similar to percentage channels for stretch and mean reversion.",
  "Nasdaq Advance Decline": "Advance/decline breadth specific to Nasdaq issues. Useful for tech-heavy risk appetite confirmation.",
  "Negative Volume Index": "Cumulative index that updates primarily on down-volume days. Traditionally linked to “smart money” activity hypotheses.",
  "Net Change": "Absolute or percent change from a prior close. The simplest momentum/performance snapshot.",
  "Net Volume": "Signed volume for the bar (up-volume minus down-volume, or close-direction signed volume). A per-bar participation pulse, not full bid/ask delta unless the feed is aggressor-signed.",
  "New High New Low Index": "Breadth of stocks making new highs versus new lows. Expands in healthy trends; divergences can flag internal weakness.",
  "NFP (Non-Farm Payrolls)": "U.S. monthly jobs report excluding farm workers. Major macro catalyst for FX, yields, and equity volatility.",
  "OBV (On Balance Volume)": "Cumulative volume added on up closes and subtracted on down closes. Confirms trends or warns via price/OBV divergence.",
  "Open Interest": "Outstanding futures/options contracts not yet closed. Rising OI with trend can confirm commitment; falling OI can mark liquidation.",
  "Option Delta": "Rate of change of option price versus underlying price. Near 1/−1 ≈ stock-like; near 0 ≈ little directional sensitivity.",
  "Option Gamma": "Rate of change of delta versus underlying. High gamma means delta (and hedges) can shift quickly near the strike.",
  "Option Theta": "Time decay of an option’s value. Negative theta for long options means value erodes as expiration approaches, all else equal.",
  "Option Vega": "Sensitivity of option price to implied volatility. Long vega benefits when IV rises; short vega benefits when IV falls.",
  "Oscillator of Moving Average": "Oscillator formed from the difference or ratio of moving averages (OsMA-style). Highlights crossover momentum.",
  "Parabolic SAR": "Stop-and-reverse dots that trail price. Flips side when price crosses the SAR—used for trailing stops and trend exits.",
  "Percent B": "Bollinger metric locating close within the bands (0 = lower band, 1 = upper). Outside 0–1 means a band breakout.",
  "Percent Price Oscillator": "MACD expressed as a percentage of the slow MA (PPO). Makes momentum comparable across different price levels.",
  "Pivot Points": "Classic floor-trader levels (PP, R1–R3, S1–S3) from prior period OHLC. Widely used for intraday S/R.",
  "Positive Volume Index": "Cumulative index updating mainly on up-volume days. Traditionally associated with crowd/public participation.",
  "PPO": "Percent Price Oscillator (short name). Percentage MACD variant for cross-asset momentum comparison.",
  "Price Action Channel": "Channel built from short smoothed highs/lows (often Heikin-Ashi based). Breaks can mark momentum shifts.",
  "Price Oscillator": "Difference between two moving averages of price (absolute form). Similar intuition to MACD without the signal complexity.",
  "Price Rate of Change": "Percent (or absolute) change in price over N bars. Classic momentum speedometer.",
  "Price Volume Trend": "Cumulative volume scaled by percent price change. Related to OBV but weights by the size of the move.",
  "Put Call Ratio": "Options volume or OI of puts divided by calls. High ratios can signal fear (contrarian bullish); low ratios signal complacency.",
  "Qstick Indicator": "Smoothed difference of open and close. Positive Qstick shows persistent buying closes; negative shows selling closes.",
  "Quadrant Lines": "Horizontal lines dividing a recent price range into four equal parts for structure and target framing.",
  "Rate of Change": "Momentum as percent change over a lookback (ROC). Crosses of zero and divergences are common signals.",
  "Relative Strength Index (RSI)": "Wilder momentum oscillator (0–100) of average gains vs losses. Classic 70/30 (or 80/20) extremes and centerline (50) reads.",
  "Relative Vigor Index": "Compares close−open to high−low vigor, smoothed with a signal line. Measures conviction of directional closes.",
  "Renko Trend": "Brick-based trend view that ignores time and focuses on fixed price movement. Filters noise to clarify trend swings.",
  "Risk Reward Ratio": "Potential reward divided by potential risk for a planned trade (e.g., 2R). Position management metric, not a price oscillator.",
  "ROC": "Rate of Change (short name). Momentum gauge of how far price has traveled over N periods.",
  "Rolling Volatility": "Trailing-window standard deviation (or similar) of returns. Updates continuously to track current realized risk.",
  "Schaff Trend Cycle": "Cycle oscillator combining MACD ideas with stochastic smoothing. Designed to reduce lag in cyclical markets.",
  "Seasonal Index": "Historical average performance by calendar period. Highlights seasonal tendencies—not a guarantee of future paths.",
  "Sharpe Ratio": "Excess return per unit of total volatility. Higher Sharpe means better risk-adjusted performance (ex-post or ex-ante).",
  "Slow Stochastic": "Smoothed stochastic %K/%D. Less noisy than fast stochastic; still maps closes into the high-low range for timing.",
  "SMA (Simple Moving Average)": "Unweighted average of the last N closes. Foundational trend filter and dynamic support/resistance.",
  "Smoothed Moving Average": "MA variant with heavier smoothing (RMA/SMMA style). Slower but steadier than SMA/EMA.",
  "Sortino Ratio": "Excess return per unit of downside deviation. Focuses on harmful volatility unlike Sharpe’s total volatility.",
  "Spread Indicator": "Tracks the price difference between two instruments or legs. Used in pairs, basis, and relative-value trading.",
  "Standard Deviation": "Statistical dispersion of price or returns around the mean. Building block of Bollinger Bands and risk models.",
  "Standard Error": "Uncertainty of a regression estimate. Narrower error means a tighter fit of price to the regression line.",
  "Stochastic Momentum Index": "Closer-range stochastic focusing on the midpoint of the high-low range. Often smoother than classic stochastic.",
  "Stochastic RSI": "Stochastic applied to RSI values instead of price. Very sensitive; useful for fine-tuning RSI timing inside trends.",
  "SuperTrend": "ATR-based trailing trend line that flips when price closes through it. Popular for clean trend following overlays.",
  "Support and Resistance": "Horizontal (or zoned) price levels where buying or selling interest previously emerged. Core price-action structure.",
  "Swing Index": "Wilder index accumulating intraday/open-close relationships to estimate swing direction and strength.",
  "T3 Moving Average": "Tillson T3—multiply-smoothed EMA variant aiming for less lag and less overshoot than simple cascades of EMAs.",
  "TEMA": "Triple Exponential Moving Average. Further reduces lag versus EMA/DEMA for faster trend tracking.",
  "Tick Index": "Intraday breadth of upticks vs downticks (often NYSE). Extreme readings can mark short-term exhaustion.",
  "Time Segmented Volume": "Volume study segmented by time to compare participation across sessions or intervals.",
  "TRIN (Arms Index)": "Ratio of advancers/decliners to up volume/down volume. TRIN > 1 often bearish breadth; < 1 often bullish breadth.",
  "Triple EMA": "Another name/use of TEMA—triple-smoothed EMA construction for responsive trend lines.",
  "TRIX": "One-period rate of change of a triple-smoothed EMA. Zero-line and signal-line crosses mark momentum polarity with heavy smoothing.",
  "Triple Top Bottom": "Reversal chart pattern with three similar highs (top) or lows (bottom). Confirmation usually needs a neckline break.",
  "True Strength Index": "Double-smoothed momentum oscillator of price change. Signal-line crosses and divergences help time swings.",
  "Turtle Channels": "Donchian-style breakout channels used by the Turtle traders (e.g., 20-day entry / 10-day exit variants).",
  "Ulcer Index": "Drawdown-based risk measure emphasizing depth and duration of declines from recent peaks.",
  "Ultimate Oscillator": "Williams oscillator blending three timeframes of buying pressure to reduce false divergence signals.",
  "Unemployment Rate": "Share of labor force unemployed. Macro input for growth, wages, and monetary-policy expectations.",
  "Upside Downside Ratio": "Ratio of upside volume (or advances) to downside volume (or declines). Breadth confirmation tool.",
  "Value Area": "In Market Profile, the price range containing a set share (often ~70%) of session volume/time. Defines “fair value.”",
  "Variable Moving Average": "Adaptive MA that speeds up in trends and slows in chop using a volatility or efficiency ratio.",
  "Vertical Horizontal Filter": "Measures how much price trended versus chopped over N bars. High VHF favors trend systems; low favors ranges.",
  "VIX": "CBOE Volatility Index—implied volatility of short-dated S&P 500 options. “Fear gauge” for expected equity turbulence.",
  "Volume": "Shares/contracts traded in a period. Confirms moves when rising with trend; warns on dry-up or climactic spikes.",
  "Volume Delta": "Difference between aggressive buy and sell volume within a bar. Order-flow read of who initiated the move.",
  "Volume Oscillator": "Difference/ratio of short vs long volume moving averages. Highlights surges or contractions in participation.",
  "Volume Profile": "Histogram of volume by price level (not by time). Locates high-volume nodes, lows, and POC for auction structure.",
  "Volume Rate of Change": "Percent change in volume over N bars. Flags accelerating or decelerating participation.",
  "Volume Weighted Average Price (VWAP)": "Average price weighted by volume, usually reset each session. Benchmark for institutional execution and intraday bias.",
  "Volume Weighted Moving Average": "Moving average that weights each close by that bar's volume. Diverges from a same-length SMA when high-volume bars dominate the average.",
  "Vortex Indicator": "VI+ and VI− lines from true-range-normalized up/down movements. Crossovers aim to catch trend reversals early.",
  "Weighted Moving Average": "MA that linearly weights recent prices more than older ones. Faster than SMA, typically slower than EMA.",
  "Williams %R": "Momentum oscillator from 0 to −100 comparing close to the recent high-low range. Similar to stochastic, inverted scale.",
  "Williams Accumulation Distribution": "Cumulative price-pressure line using true range relationships (Williams AD). Divergences can precede turns.",
  "Wolfe Waves": "Natural-rhythm wave pattern seeking a breakout “EPA” target line. Used for timed reversal/continuation projections.",
  "XTL Trend Indicator": "Extended trend-line / trend-filter style overlay used to classify bullish vs bearish regime regimes on a chart.",
  "Yield Curve": "Plot of yields across maturities. Steep, flat, or inverted shapes inform growth and recession risk narratives.",
  "Yield Spread": "Difference between two yields (e.g., 10y−2y or credit spreads). Tracks risk appetite and relative value.",
  "Zig Zag Indicator": "Filters swings by a minimum percent/point move. Clarifies pivot structure; repaints by design until confirmed.",
  "Z-Score": "Number of standard deviations price (or a metric) sits from its mean. High |z| implies statistical stretch.",
  "Zero Lag EMA": "EMA variant engineered to cancel much of classic EMA lag while retaining smoothness.",
  "Zero Line Cross": "Generic signal class: an oscillator crossing above/below zero to mark momentum polarity changes.",
  "ZLEMA": "Zero-Lag Exponential Moving Average (Ehlers-style). Seeks EMA responsiveness with reduced delay.",
};
