import { createPost, getPost, listDueQueuedPosts, listPosts, updatePost } from './store';
import { defaultPublishMode, getSocialOsConfig, publishPost } from './publisher';
import {
  cadenceStatus,
  detectDueSlot,
  getCadencePlatforms,
  markSlotFired,
} from './cadence';
import { buildTemplate } from './templates';
import type { SocialPlatform, TemplateKind } from './types';

let timer: ReturnType<typeof setInterval> | null = null;
let ticking = false;

const TEMPLATE_ROTATION: TemplateKind[] = [
  'clarity_cta',
  'education_tip',
  'feature_highlight',
  'market_lesson',
  'founder_story',
];

function autoTemplateEnabled(): boolean {
  const v = (process.env.SOCIAL_OS_AUTO_TEMPLATE || '1').toLowerCase();
  return v !== '0' && v !== 'false' && v !== 'no';
}

function pickTemplateKind(slot: string): TemplateKind {
  const idx = ['05:00', '09:00', '15:00', '18:00'].indexOf(slot);
  return TEMPLATE_ROTATION[(idx >= 0 ? idx : 0) % TEMPLATE_ROTATION.length];
}

function nextQueuedForPlatform(platform: SocialPlatform) {
  const due = listDueQueuedPosts().filter((p) => p.platform === platform);
  if (due[0]) return due[0];
  const queued = listPosts({ status: 'queued', platform });
  if (queued[0]) return queued[0];
  const drafts = listPosts({ status: 'draft', platform });
  return drafts[0] || null;
}

async function ensurePostForPlatform(platform: SocialPlatform, slot: string) {
  const existing = nextQueuedForPlatform(platform);
  if (existing) {
    if (existing.status === 'draft') {
      return updatePost(existing.id, {
        status: 'queued',
        scheduledAt: new Date().toISOString(),
      })!;
    }
    return existing;
  }

  if (!autoTemplateEnabled()) return null;

  const draft = buildTemplate(pickTemplateKind(slot), platform, {
    topic: 'chart-first clarity',
    feature: 'ClearPath market intelligence terminal',
  });
  return createPost({
    platform,
    body: draft.body,
    title: draft.title,
    linkUrl: draft.linkUrl,
    hashtags: draft.hashtags,
    status: 'queued',
    scheduledAt: new Date().toISOString(),
    publishMode: defaultPublishMode(),
    source: 'template',
    meta: { cadenceSlot: slot, kind: draft.kind, autoGenerated: true },
  });
}

export type CadenceTickResult = {
  processed: number;
  published: number;
  failed: number;
  dryRun: number;
  packaged: number;
  slot?: string;
  slotKey?: string;
  details: string[];
};

function applyPublishResult(postId: string, result: Awaited<ReturnType<typeof publishPost>>) {
  const status =
    result.mode === 'package' ? ('packaged' as const) : ('published' as const);
  return updatePost(postId, {
    status,
    publishedAt: new Date().toISOString(),
    publishMode: result.mode,
    externalIds: {
      platformPostId: result.platformPostId,
      packagePath: result.packagePath,
    },
  });
}

/** Process due manually-queued posts (scheduledAt), independent of daily slots. */
async function processManualQueue(): Promise<{
  published: number;
  failed: number;
  dryRun: number;
  packaged: number;
  details: string[];
}> {
  let published = 0;
  let failed = 0;
  let dryRun = 0;
  let packaged = 0;
  const details: string[] = [];
  const due = listDueQueuedPosts().filter((p) => !p.meta?.cadenceSlot);
  for (const post of due) {
    updatePost(post.id, { status: 'publishing', lastError: undefined });
    try {
      const result = await publishPost(getPostRequired(post.id));
      applyPublishResult(post.id, result);
      if (result.dryRun) dryRun += 1;
      else if (result.mode === 'package') packaged += 1;
      else published += 1;
      details.push(`manual ${post.id} → ${result.mode}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      updatePost(post.id, { status: 'failed', lastError: message });
      failed += 1;
      details.push(`manual ${post.id} failed: ${message}`);
    }
  }
  return { published, failed, dryRun, packaged, details };
}

function getPostRequired(id: string) {
  const post = getPost(id);
  if (!post) throw new Error(`Post ${id} missing`);
  return post;
}

/** Fire one daily cadence slot: one post per configured platform. */
export async function runCadenceSlot(slot: string, key: string): Promise<CadenceTickResult> {
  const platforms = getCadencePlatforms();
  const details: string[] = [];
  let published = 0;
  let failed = 0;
  let dryRun = 0;
  let packaged = 0;

  for (const platform of platforms) {
    try {
      const post = await ensurePostForPlatform(platform, slot);
      if (!post) {
        details.push(`${platform}: skipped (empty queue, auto-template off)`);
        continue;
      }
      updatePost(post.id, {
        status: 'publishing',
        lastError: undefined,
        meta: { ...post.meta, cadenceSlot: slot, cadenceKey: key },
      });
      const fresh = getPostRequired(post.id);
      const result = await publishPost(fresh);
      applyPublishResult(post.id, result);
      if (result.dryRun) dryRun += 1;
      else if (result.mode === 'package') packaged += 1;
      else published += 1;
      details.push(`${platform}: ${post.id} → ${result.mode}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      failed += 1;
      details.push(`${platform}: failed — ${message}`);
      console.warn(`[Social OS] Cadence ${key} ${platform}:`, message);
    }
  }

  markSlotFired(key, details.join('; '));
  return {
    processed: platforms.length,
    published,
    failed,
    dryRun,
    packaged,
    slot,
    slotKey: key,
    details,
  };
}

export async function tickSocialOsScheduler(): Promise<CadenceTickResult> {
  if (ticking) {
    return {
      processed: 0,
      published: 0,
      failed: 0,
      dryRun: 0,
      packaged: 0,
      details: ['tick already in progress'],
    };
  }
  ticking = true;
  try {
    const manual = await processManualQueue();
    const due = detectDueSlot();
    if (!due) {
      return {
        processed: manual.published + manual.failed + manual.dryRun + manual.packaged,
        published: manual.published,
        failed: manual.failed,
        dryRun: manual.dryRun,
        packaged: manual.packaged,
        details: manual.details.length ? manual.details : ['no cadence slot due'],
      };
    }

    console.log(`[Social OS] Cadence slot due: ${due.key} (${due.timeZone})`);
    const cadence = await runCadenceSlot(due.slot, due.key);
    return {
      processed: cadence.processed + manual.published + manual.failed + manual.packaged,
      published: cadence.published + manual.published,
      failed: cadence.failed + manual.failed,
      dryRun: cadence.dryRun + manual.dryRun,
      packaged: cadence.packaged + manual.packaged,
      slot: cadence.slot,
      slotKey: cadence.slotKey,
      details: [...manual.details, ...cadence.details],
    };
  } finally {
    ticking = false;
  }
}

export function startSocialOsScheduler(): void {
  if (timer) return;
  if ((process.env.SOCIAL_OS_SCHEDULER || '1').toLowerCase() === '0') {
    console.log('[Social OS] Scheduler disabled (SOCIAL_OS_SCHEDULER=0)');
    return;
  }
  const config = getSocialOsConfig();
  const status = cadenceStatus();
  console.log(
    `[Social OS] Direct publisher ON — middlemen=none timezone=${status.timezone} slots=${status.slots.join(',')} platforms=${status.platforms.join(',')} dryRun=${config.dryRun} credentials=${config.platformsConfigured}/${config.platformsTotal}`
  );
  const intervalMs = Number(process.env.SOCIAL_OS_TICK_MS) || 60_000;
  setTimeout(() => {
    void tickSocialOsScheduler();
  }, 12_000);
  timer = setInterval(() => {
    void tickSocialOsScheduler();
  }, intervalMs);
  timer.unref?.();
}

export function stopSocialOsScheduler(): void {
  if (timer) {
    clearInterval(timer);
    timer = null;
  }
}

export { cadenceStatus };
